# Generated by Django 5.1.7 on 2025-03-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetracker', '0002_worksession_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Timetracker.project'),
        ),
    ]
