# Generated by Django 5.1.7 on 2025-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetracker', '0003_worksession_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
